config/routes.rb
Rails.application.routes.draw do

  match "/pages_delete_selected" => "pages#delete_selected", :as => :delete_selected, via: :all
  root 'pages#index'
end

app/models/user.rb
class User < ActiveRecord::Base

  def self.create_100
    100.times do
      User.create(name: FFaker::Name.name)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  expose(:users)

  def index
    if User.count == 0
      User.create_100
    end
  end

  def delete_selected
    User.where(id: params[:users_ids]).delete_all
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SampleDeleteMultipleRecordsAtOnce</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/index.html.haml
%h1 Delete multiple records at once
%h2 There are currently #{users.count} loaded on this page
%h3 if there are 0 there will be 100 more loaded
= simple_form_for :user, :url => delete_selected_path, :method => :delete do |f|
  %table
    %tr
      %td Select
      %td Name
    - users.each do |user|
      %tr
        %td= check_box_tag 'users_ids[]', user.id 
        %td= user.name
    %tr
      %td
      %td= f.button :submit, 'Delete Selected'